# Generated by Django 3.1.5 on 2021-02-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
