# Generated by Django 3.1.5 on 2021-02-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20210213_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='posted_at',
        ),
    ]
