# Generated by Django 3.1.5 on 2021-02-14 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_remove_photo_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
